### ISSUE TITLE
Hungarian Channels

### ISSUE THREAD

**Issue by sirjohn771103** [epgshare01/share01#100]
hello, please update the Hungarian channels.

These channels are not anymore. They are closed, not exist channels anymore. 

1.Music.Channel.(HD).hu
DIGI.Animal.World.(HD).hu
DIGI.Life.(HD).hu
DIGI.Sport.1.(HD).hu
DIGI.Sport.2.(HD).hu
DIGI.Sport.3.(HD).hu
DIGI.World.(HD).hu
Film.Now.hu
H!T.Music.hu

Please, pick up these channels:
Match.4.(HD).hu
M3.(HD).hu

Thank you for your nice service.

**Comment by epgshare01** [comment]
Switched to new source. Wait a day for new upload.
