### ISSUE TITLE
Missing UK epg

### ISSUE THREAD

**Issue by adamosborne83** [epgshare01/share01#102]
Good evening,
New user, just playing due to issues on m3u4u at present.
But there does not seem to be a listing for MTV90s
5Action,
Legend,
Reality Xtra,
News Media,
Sky Nature,
NBC News Now,
Sky Cinema Blockbuster,
BT Sports 5-10,
BT Sport Ultimate,
MTV Live,
Clubbing TV,
Gemporia and Craft,

Apologies if I am missing the correct format etc.

**Comment by epgshare01** [comment]
All added except:
News Media
Sky Cinema Blockbuster
Clubbing TV
Gemporia and Craft

BT SPorts channels already existed.

Wait for tomorrow night's upload.
