### ISSUE TITLE
File epg_ripper_US_LOCALS2.xml.gz can not exctrat

### ISSUE THREAD

**Issue by tortolo2022** [epgshare01/share01#106]
I am trying to extract the file using gzip or gunzip in Linux, but the command return an errror: gzip: /home/scmjourn/public_html/epg_ripper_US_LOCALS2.xml.gz: not in gzip format

Only I can extract this file using MacOs file manager or Windows, but directly in command line in Unix is impossible. I am using an script to run the complete commands (get the file, extract the file and put the file on TVheadend). 

Please any solution,

Thanks,

Jairo

**Comment by tortolo2022** [comment]
Hi, I got the solution using the download link and pass it to script. But there is a problem the permanent link download a file that is impossible to extract.

Thanks,

Jairo

**Comment by epgshare01** [comment]
Not my department. :P
