### ISSUE TITLE
Channels Needs Added

### ISSUE THREAD

**Issue by tortolo2022** [epgshare01/share01#108]
CBS News is not included, CBSN is not included. And the more Weathernation Channels for the more important cities needs added. 

Thanks for your work ahead of time!

Bye,

Jairo Cárdenas

**Comment by agentsix1** [comment]
So cbs news has a epg. But all it shows is. CBS News

Id
CBS.News.us

**Comment by epgshare01** [comment]
Not going to add for every city.

**Comment by tortolo2022** [comment]
OK is right
