### ISSUE TITLE
epg_ripper_US_LOCALS2.xml.gz - EPG one hour behind

### ISSUE THREAD

**Issue by benevenstanciano** [epgshare01/share01#111]
It looks like the EPG is incorrect. The EPG seems like it's one hour late. Can anybody else confirm?

**Comment by Kyopia** [comment]
Yes

**Comment by epgshare01** [comment]
I believe that I found the issue. Let me know if tonight's upload is fixed.

**Comment by benevenstanciano** [comment]
Thanks. I can let you know in the morning. Do you know what the issue might have been and if it affected other pulls?

**Comment by Kyopia** [comment]
It's fixed. Thank you.

**Comment by benevenstanciano** [comment]
I can see that it's fixed for some channels, but for example WCBS-DT1, 4:30am news is showing at 5:30am, etc.

**Comment by benevenstanciano** [comment]
Fix now, thank you
