### ISSUE TITLE
Add Missing Indian channel -- Mangalam TV

### ISSUE THREAD

**Issue by bhanuagarwal73** [epgshare01/share01#116]
Please add MangalamTV.in
![image](https://user-images.githubusercontent.com/38572421/196124525-288a00f9-a05f-456d-8dab-3efef4f7d45c.png)

![image](https://user-images.githubusercontent.com/38572421/196124482-6478fd63-c753-4176-b5fb-7b96d5964cab.png)

**Comment by epgshare01** [comment]
I am not able to find this one. Sorry.
