### ISSUE TITLE
Gma News TV and CNN Philippines

### ISSUE THREAD

**Issue by melchorphc** [epgshare01/share01#119]
The two channels has the same program.. gma news tv guide uses cnn ph guide..

GMA.News.TV.ph
CNN.Philippines.ph

https://github.com/epgshare01/share01/blob/master/epg_ripper_PH2.xml.gz

**Comment by melchorphc** [comment]
Any update sir?

**Comment by epgshare01** [comment]
This seems to be a source issue. No fix until they fix it.
