### ISSUE TITLE
epg_ripper_BR1

### ISSUE THREAD

**Issue by rolimrrx** [epgshare01/share01#127]
Hello noble contributor. Some channels are no longer updating. Are they:
  BIS.HD.br
Canal.Brasil.HD.br
Combat.HD.br
Globo.News.HD.br
Globo.SP.HD.br
Megapix.HD.br
Mode.Travel.br
Multishow.HD:.br
Premiere.HD2.br
Premiere.HD.3.br
Premiere.HD.4.br
Premiere.HD.5.br
Premiere.HD6.br
Premiere.HD7.br
Premiere.HD.br
Sportv.2.HD.br
SporTV.3.HD.br
Sportv.HD.br
Studio.Universal.br
Syfy.br
Universal.TV.HD.br
Viva.HD.br

**Comment by epgshare01** [comment]
Looks as though source is having issues.
