### ISSUE TITLE
Channel name change and missing EPG

### ISSUE THREAD

**Issue by le4689** [epgshare01/share01#135]
Premier Sports (Premier.1.HD.uk & Premier.2.HD.uk) have been changed to the below and are currently showing no EPG:
Viaplay Sports 1 (Previously Premier Sports 1): https://www.tvguide.co.uk/mobile/channellisting.asp?ch=715
Viaplay Sports 2 (Previously Premier Sports 2): https://www.tvguide.co.uk/mobile/channellisting.asp?ch=1229

It also seems that Sky Sports Football (SkySp.F'ball.HD.uk & SkySp.F'ball.uk) have no EPG generated
https://www.tvguide.co.uk/mobile/channellisting.asp?ch=1103

**Comment by epgshare01** [comment]
Viaplay.Sports.1.HD.uk
Viaplay.Sports.2.HD.uk
Viaplay.Xtra.HD.uk

Issue @ source for Sky Sport Football. Wait for it to be fixed.
