### ISSUE TITLE
De Pelicula US and Mexico

### ISSUE THREAD

**Issue by Mikhel** [epgshare01/share01#136]
**Request:** If possible could you add the following channels to **_epg_ripper_US1.xml.gz_**? they already are referenced in **_epg_ripper_US1.txt_** but are not included in the XML.GZ

De.Película.Clásico.(DPCLA).us
De.Película.EUA.(USA).(DEPEL).us

And to **_epg_ripper_MX1.xml.gz_** the following:

**De Película** ---> DePeliculaLatinAmerica.mx
**De Película Clásico** --> DePeliculaClasico.mx
**De Pelicula HD** ---> DePelicula.mx

The first two from gatotv mexico:
https://www.gatotv.com/canal/de_pelicula
https://www.gatotv.com/canal/de_pelicula_clasico

And **De Película HD** from:
from: https://mi.tv/mx/canales/de-pelicula-hd

In there **mi.tv** there is a second **De Pelicula** (https://mi.tv/mx/canales/de-pelicula) but it is the same as the **De Pelicula LatinAmerica** from **gatotv** (https://www.gatotv.com/canal/de_pelicula), in México the "**De pelicula HD**" is branded "**De pelicula Plus**" with different programming.

Thanks and Saludos :)

**Comment by epgshare01** [comment]
These exist with data already:
De.Película.Clásico.(DPCLA).us
De.Película.EUA.(USA).(DEPEL).us

Added:
De.Película.HDTV.(Latin.America).(DPELICHD).mx
Canal.De.Película.mx
Canal.De.Película.(Multiplex).mx
Canal.De.Película.Clásico.mx
