### ISSUE TITLE
epg seems to be empty

### ISSUE THREAD

**Issue by wuppiwuppi** [epgshare01/share01#138]
hi, 

epg seems to be empty https://github.com/epgshare01/share01/blob/master/epg_ripper_DE1.xml.gz?raw=true

any infrastructural issues currently?

br

**Comment by epgshare01** [comment]
Source issue. Waiting for a fix.

**Comment by wuppiwuppi** [comment]
Sure no problem. Any eta available?

**Comment by epgshare01** [comment]
I have a new source. Hopefully it will upload tonight.

**Comment by wuppiwuppi** [comment]
@epgshare01 looks good. had to re-assign all of them, due to new names. 
but "vox up" is misisng.
