### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ajtel** [epgshare01/share01#14]
How can i pull epg ... the xml looks great.. where is the url to pull.?

**Comment by epgshare01** [comment]
Use the Raw links from the Download buttons.

**Comment by ajtel** [comment]
> Use the Raw links from the Download buttons.

can you pvt msg? i download link to our server... but epg does not pull when we ask server sasy not epg info  obvius chaning epg tag in our side)

**Comment by epgshare01** [comment]
Use the URL from the download button.

![image](https://user-images.githubusercontent.com/65776741/128617384-a71a8f19-34ac-4f18-8a26-0f7c75e60839.png)

**Comment by ajtel** [comment]
Yes I do.... Bue epg does not pullingMigrando al Futuro…La nueva Forma de ver Sus telecomunicaciones Ing. André Vivar Balderrama B. Dirección de Operación en América ***@***.***: 5010OFICINA MEXICO:CDMX +52 (55) 8526-5000 y.                                                +52 (55) 1205-5050 GDL: +52 (33)1032-5050MONTERREY: +52(81)1111-5000  y +52(81)1112-5000LEON: +52 (477) 278-5000CUERNAVACA: +52 (777) 247-5000VERACRUZ +52(229)180-0000TABASCO +52(993)171-1111MERIDA: +52 (999) 293-5000CANCÚN: +52 (998) 261-5000PUEBLA: +52 (222) 552-2222TIJUANA: +52(664)140-0000USA FLORIDA OFFICE +1-407-214-6060UK OFFICE: +44(20)35198129Contacto SIPBROKER: *735 5010 Directos:MEX DF +52 (55) 8526-5010+52 (55) 5989-0788: andrevivarUSA CALIFORNIA: +1 (619) 537-8838MONTREAL QB, CA. +1(438) 338-4211TORONTO ON, CA +1(647) 875-7510       Piense en el medio ambiente antes de imprimir este mensaje!"CONFIDENCIALIDAD. Este correo electrónico y/o el material adjunto es para uso exclusivo de la persona o entidad a la que expresamente se la ha enviado, y puede contener información confidencial o material privilegiado: Si usted no es el destinatario legítimo del mismo, por favor repórtelo inmediatamente al remitente de este correo y bórrelo. Cualquier revisión, retransmisión, difusión o cualquier otro uso de este correo, por personas o entidades distintas a las del destinatario legítimo, queda expresamente prohibido. Este correo electrónico no pretende ni debe ser considerado como constitutivo de ninguna relación legal, contractual o de otra índole similar"
-------- Mensaje original --------De: epgshare01 ***@***.***> Fecha: 7/8/21  19:58  (GMT-06:00) A: epgshare01/share01 ***@***.***> CC: AJTEL Communications Network Group LLC ***@***.***>, Author ***@***.***> Asunto: Re: [epgshare01/share01] Question (#14) 
Use the URL from the download button.

**Comment by epgshare01** [comment]
Send me an email @ epgshare01.gmail.com
