### ISSUE TITLE
Unable to import epg_ripper_US_LOCALS2.xml.gz

### ISSUE THREAD

**Issue by JaceFelicity** [epgshare01/share01#142]
I attempted to import epg_ripper_US_LOCALS2.xml.gz in both Emby and XTeVe, but I got the following errors - 

Emby - System.Xml.XmlException: System.Xml.XmlException: '>' is an unexpected token. The expected token is '='. Line 16, position 76.

XTeVe - 2023-01-08 16:32:08 [xTeVe] [ERROR] expected element type  but have  () - EC: 0

I have attached a picture of the full log from Emby. If I could get some help with this, I would rly appreciate it.

![Love0000](https://user-images.githubusercontent.com/122235395/211221695-2b642bf4-b4c8-4c21-90c0-e9b893eb021e.png)

**Comment by epgshare01** [comment]
I do not support applications.
