### ISSUE TITLE
epg_ripper_MX1

### ISSUE THREAD

**Issue by ajtel** [epgshare01/share01#16]
is not in guide.. can you add? 

Channel 6.1 Mexico City from Multimedios
Channel 6.1 Monterrey from Multimedios  
Channel XHTV 4.1 MEXICO CITY
Channel 3.1 Imagen Multimedios Mexico City
Channel 8.1 Mexico City
Channel  9.1 Mexico City
Channel 4.1,4.2,4.3.,4.4 from Leon Gto, MEX 
is not In list.. can you add?

**Comment by epgshare01** [comment]
Sorry, but I only have time for managing US locals. :(
