### ISSUE TITLE
any chance of a master file (eg. all into 1 epg, as pluto u have split over 2 epgs)

### ISSUE THREAD

**Issue by bitsbb01** [epgshare01/share01#20]
any chance of a master file (eg. all into 1 epg, as pluto u have split over 2 epgs) and most m3u files can only have 1 epg, therefore not all the channels are covered. 

For example i have a master list that has all pluto, airy.tv, us, uk and others.

**Comment by grand8400** [comment]
Hello together,
which link should i put in my tivimate player to get all_sources epg?
Many thanks

**Comment by bitsbb01** [comment]
epg_ripper_ALL_SOURCES1.xml.gz, use the download link and place that in tivimate epg, i would also download it and make sure that your own m3u list matches it.
