### ISSUE TITLE
Please add ION TV West

### ISSUE THREAD

**Issue by CHJ85** [epgshare01/share01#22]
Hi there. In your US local list, you've got the east version of ION TV.
Could you please add EPG for west?

EDIT: Could you also add NBC Bay Area please?
Thanks in advance and thanks for your hard work.

**Comment by MLBStream** [comment]
workaround that I do for west and east channels, I use tag **tvg-shift="3"** on the m3u list to match east data to west channels. Maybe it can help you too.

**Comment by CHJ85** [comment]
Thanks @MLBStream I'll try that
