### ISSUE TITLE
Please add FETV and RewindTV

### ISSUE THREAD

**Issue by CHJ85** [epgshare01/share01#24]
Hi there. Could you please add FETV (Family Entertainment TV) and the new RewindTV?
Thanks for your work.

**Comment by epgshare01** [comment]
Added. Wait for tomorrow's upload.

**Comment by CHJ85** [comment]
Thank you!

**Comment by CHJ85** [comment]
I see you added FETV to the US1 list.
But it's a free OTA channel, so please add it to the USLocal2 epg.

**Comment by rick999999** [comment]
where can i find the index for RewindTV ?thx~!

**Comment by rick999999** [comment]
the Rewind.us in 'epg_ripper_US_LOCALS2.txt' is incorrect
