### ISSUE TITLE
Please add EPG for Rewind TV (US EST) thx!!!

### ISSUE THREAD

**Issue by rick999999** [epgshare01/share01#32]
here's the schedule
https://rewindtv.com/interactive-schedule/

or this one
https://www.tvpassport.com/tv-listings/stations/rewind-tv-us-wpixdt4-new-york-ny/32844

thx a lot !!!

**Comment by rick999999** [comment]
the Rewind.us in 'epg_ripper_US_LOCALS2.txt' is incorrect
plz check it out!
thx a lot!!!

**Comment by epgshare01** [comment]
Fixed.
