### ISSUE TITLE
Uk tv missing most epg

### ISSUE THREAD

**Issue by ac3nl** [epgshare01/share01#37]
Uk tv is missing a lot of epg data
Could you please restart scrubbing?

**Comment by epgshare01** [comment]
Some IDs have changed.

**Comment by ac3nl** [comment]
Even after re-assigning them, no content….

**Comment by epgshare01** [comment]
Sorry about that. Should be fixed now hopefully.

**Comment by ac3nl** [comment]
That did it , thank you!
