### ISSUE TITLE
Hungarian EPG

### ISSUE THREAD

**Issue by sirjohn771103** [epgshare01/share01#38]
hello, 
Can you pick up these Hungarian channels?
M3: [https://tvepg.eu/hu/hungary/channel/m3#now](url)
Kölcsey TV: [https://tvepg.eu/hu/hungary/channel/kolcsey_tv#now](url)
Thank you.

**Comment by gyiku** [comment]
Hi,
Please  add 
Spektrum Home: https://tvepg.eu/hu/hungary/channel/spektrum_home#now
as well.
Thank you.

**Comment by epgshare01** [comment]
All added.

**Comment by remex74** [comment]
Dear epgshare01,

Can you add these Hungarian channels, too?

Story 4 TV:
https://tvepg.eu/hu/hungary/channel/story4#now
https://www.tvmustra.hu/tvmusor/STORY4
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/95-Story-TV4-heti.html

AXN White:
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/8-AXN-White-Crime-heti.html

AXN Black:
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/9-AXN-Black-Sci-fi-heti.html

Miskolc TV:
https://tvepg.eu/hu/hungary/channel/miskolc_tv#now

Trimedio TV:
https://trimedio.hu/musorujsag

Thank you!
