### ISSUE TITLE
Korean EPG info

### ISSUE THREAD

**Issue by yahn01** [epgshare01/share01#4]
Hello, I would appreciate if you couldadd Korea epg 
I am able to figure out to generate xml for korean channels if you need info I will help you so that korean epg can also be here in your share01. 
I will send files I use to generate so please let me know xml.
My email address is yahn645@gmail.com

**Comment by epgshare01** [comment]
Send me what you have and I will check it out.

**Comment by epgshare01** [comment]
Closing as there was no response.

**Comment by yahn01** [comment]
Sorry I saw message now. I will send the things by this week. Sorry for
delays.

Thanks and Regards
Ahn

**Comment by yahn01** [comment]
Dear Epgshare 01

First of all, I apologize for replying late as I didnt notice you sent
email until yesterday.
Thank you very much doing a great work to share EPG file for everyone to
use.
Incase if you are using webgraber plus to make EPG file then is it possible
to use
http://webgrabplus.com/epg-channels#s146
then to host korean epg.xml file?

If not, https://github.com/wiserain/epg2xml
This is Korean person who developed  this program to create Korean EPG.xml.
it is in Korean but use to create Korean TV xml file.
Incase if you need further information, please let me know,

Thanks

Ahn
