### ISSUE TITLE
Hungarian EPG problem

### ISSUE THREAD

**Issue by remex74** [epgshare01/share01#42]
The Hungarian epg is not updated. 
The last date in the guide is January 22, 2021.
Can you fix it?

...and can you add these Hungarian channels, please?

Story 4 TV:
https://tvepg.eu/hu/hungary/channel/story4#now
https://www.tvmustra.hu/tvmusor/STORY4
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/95-Story-TV4-heti.html

AXN White:
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/8-AXN-White-Crime-heti.html

AXN Black:
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/9-AXN-Black-Sci-fi-heti.html

Miskolc TV:
https://tvepg.eu/hu/hungary/channel/miskolc_tv#now

Trimedio TV:
https://trimedio.hu/musorujsag

Thank you!

**Comment by remex74** [comment]
Dear epgshare01,

And can you add these Hungarian channels, too?

Story 4 TV:
https://tvepg.eu/hu/hungary/channel/story4#now
https://www.tvmustra.hu/tvmusor/STORY4
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/95-Story-TV4-heti.html

AXN White:
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/8-AXN-White-Crime-heti.html

AXN Black:
https://tv-musor.hirfriss.hu/mai-tv-musorujsag/9-AXN-Black-Sci-fi-heti.html

Miskolc TV:
https://tvepg.eu/hu/hungary/channel/miskolc_tv#now

Trimedio TV:
https://trimedio.hu/musorujsag

Thank you!

**Comment by epgshare01** [comment]
All added except Trimedio. Wait a day for them to show up.
