### ISSUE TITLE
Hungarian EPG again :)

### ISSUE THREAD

**Issue by remex74** [epgshare01/share01#43]
Dear epgshare,

Your project is very great! I'm so glad I can use it.
Thank you for the recent Hungarian EPG updates.
Is there any way to donate this project?

And sorry that I'm writing again, but I would have a few more comments about the Hungarian EPG.
It's almost perfect, it's just a few minor bugs.

1
Some channel guides only contain 2 days of programming, and when I download the EPG file, it only includes the previous day and the current day. Because of this, after midnight the program guide is no longer included until the next update.
An example of such a channel is M3.
The source from which you download:
https://tvepg.eu/hu/hungary/channel/m3#now
In my opinion, the tvepg.hu website always shows only two days of programming on one page.
For all EPGs grabbed from here, it would be better to build the epg based on the date instead of the #now option, and you could include more days.
example:
https://tvepg.eu/en/hungary/channel/m3/2022-01-30 (today's date, includes programs 2022-01-30 and 2022-01-31)
https://tvepg.eu/en/hungary/channel/m3/2022-02-01 (the day after tomorrow, includes 2022-02-01 and 2022-02-02)
...and so on...

2
The "History ID" channel is incomplete.
Maybe the original source of the TV guide is not accurate.

Example:

(the exactly TV guide, source: https://tv-musor.hirfriss.hu/mai-tv-musorujsag/62-History-heti.html)
13:00 Raktárvadászok
amerikai reality-sorozat
13:25 Mocsárlakók: kígyók inváziója
amerikai reality műsor, II / 1. rész
14:25 Ősi idegenek: A végső bizonyíték
amerikai dokumentumfilm sorozat, XIII / 3. rész

(and this is the contents of the epg_ripper_HU1.xml file, it's like there's every second program is missing, maybe this grabbed from "tvmustra.hu" if I am right)
`<programme start="20220130130000 +0100" stop="20220130142500 +0100" channel="History.Channel.hu">
    <title lang="hu">Raktárháborúk</title>
    <sub-title lang="hu">Arcadiai nagy számok</sub-title>
    <desc lang="hu">Az előkelő Arcadia komoly árveréssel kecsegtet. Darrell és Brandon nagy lendülettel indulnak, de lebuknak egy svindlivel.</desc>
    <date>2014</date>
    <episode-num system="onscreen">S9 E20</episode-num>
  </programme>
  <programme start="20220130142500 +0100" stop="20220130161500 +0100" channel="History.Channel.hu">
    <title lang="hu">Ősi idegenek</title>
    <sub-title lang="hu">Találkozások</sub-title>
    <desc lang="hu">Az Ősi idegenek visszaszámlálásában ezúttal a földönkívüli találkozásoké a főszerep.</desc>
    <date>2021</date>
    <episode-num system="onscreen">S13 E24</episode-num> </programme>`

Thank you in advance for your fantastic project!

**Comment by sirjohn771103** [comment]
hello!

Thank you, for your service! :)

Please, update Kölcsey TV EPG. Thank you.

Sources:
https://tvepg.eu/hu/hungary/channel/kolcsey_tv#now
https://musor.tv/mai/tvmusor/KOLCSEY_TV

**Comment by remex74** [comment]
The epg unfortunately doesn't update well, because the last days for most channels 02/02/2020 and 04/02/2012. :(

**Comment by sirjohn771103** [comment]
hello, can you get channels from musor.tv? thank you.
https://musor.tv/

**Comment by sirjohn771103** [comment]
Please, get M3 channel from here:
https://tvprofil.com/hu/tvmusor/#!kanal=m3
Thank you.

**Comment by epgshare01** [comment]
Finally I found a good source for Kölcsey TV!
Sorry it took so long.
