### ISSUE TITLE
please add two channels to "epg_ripper_BEIN1"

### ISSUE THREAD

**Issue by thijselblaso** [epgshare01/share01#51]
I'm missing the following two channels:

See [iptv-org.github.io](https://iptv-org.github.io/)

BEIN SPORTS NBA
TV-ID: BeInSportsNews.qa
https://iptv-org.github.io/epg/guides/qa/beinsports.com.epg.xml

BEIN SPORT NEWS
TV-ID: BeInNBA.qa
https://iptv-org.github.io/epg/guides/qa/beinsports.com.epg.xml

Thanks!

**Comment by epgshare01** [comment]
Data should be there today. Had code issue.
