### ISSUE TITLE
Please can you add two channels to epg_ripper_US1

### ISSUE THREAD

**Issue by thijselblaso** [epgshare01/share01#59]
I'm missing the following two channels:

See [iptv-org.github.io](https://iptv-org.github.io/)

CINE LIFE
TV-ID: CineLife.us
https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml

AMC Presents
TV-ID: AMCPresents.us
https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml

Thanks!

**Comment by epgshare01** [comment]
Use that data source if it already has the data.
