### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by audiosistem** [epgshare01/share01#61]
Thanks!Requests, several stations in RO have changed their name, is it possible to update?
PRO.2.ro - Acasa
PRO.GOLD - Acasa Gold
PRO.X - PRO Arena
Telekom.Sport.1 - Orange sport 1
Telekom.Sport.2 - Orange sport 2
Telekom.Sport.3 - Orange sport 3
Telekom.Sport.4 - Orange sport 4
And if it is not possible, thank you very much!
A beautiful day!

**Comment by epgshare01** [comment]
Done. Wait for tomorrow's upload.
