### ISSUE TITLE
Can't get HBO Zone East information

### ISSUE THREAD

**Issue by hollywooddchi** [epgshare01/share01#62]
According to the ALL_SOURCES1 list, HBO Zone (East):
</channel>
  <channel id="HBO.Zone.HDTV.(East).(HBOZHD).us">
    <url>http://www.tvguide.com</url>
    <display-name lang="en">HBO Zone HDTV (East) (HBOZHD)</display-name>
  </channel>

Looking at tvguide.com, I can't find the channel there. However, tvpassport.com has a listing for HBO Zone (East).
Is it possible to change to the tvpassport listing?
Thanks!

**Comment by epgshare01** [comment]
Use this: HBO.Zone.HDTV.(East).(HBOZHD).us
