### ISSUE TITLE
EPG data missing from XML rips

### ISSUE THREAD

**Issue by Mateus109** [epgshare01/share01#63]
Hi,
Several of the recent rips seem to be missing their EPG data (e.g. epg_ripper_FI1.xml).  Previous XML file size of epg_ripper_FI1.xml was over 3MB, now it's just 19KB.
Thanks

**Comment by Mateus109** [comment]
Hi, this issue is unresolved - data is not being correctly ripped from https://tvepg.eu/en/finland/channel/ and the XML files generated contain just channel IDs, no actual EPG data. 
Thanks

**Comment by epgshare01** [comment]
Sorry about that. I see that the source is having issues. I can wait for source to be resolved, or I can scrape a different site. If I switch sites, the IDs will probably all change.
