### ISSUE TITLE
Problem in epg_ripper_HK1.xml

### ISSUE THREAD

**Issue by engrmansoor77** [epgshare01/share01#64]
Dear Developer,
Thanks for the great job.
I noticed that since last several days, epg_ripper_HK1.xml is having some formatting problem and was not readable. I checked it with XML validate and it returned following error.

DOMDocument::load(): EntityRef: expecting ';' in file:/epg_ripper_HK1.xml

Kindly resolve it. 

Thanks.

**Comment by engrmansoor77** [comment]
line: 56262 

I checked it &apos is written in end. When i deleted it. I was all ok. Please check

**Comment by epgshare01** [comment]
I don't see that at end of today's file. Is it OK now?

**Comment by engrmansoor77** [comment]
Yes it is OK now. Thanks
