### ISSUE TITLE
epg_ripper_US1 data isn't merging in epg_ripper_ALL_SOURCES1

### ISSUE THREAD

**Issue by MLBStream** [epgshare01/share01#65]
Hi!

While **epg_ripper_US_LOCALS2** data doesn't have any problem, data from **epg_ripper_US1** doesn't appear in **epg_ripper_ALL_SOURCES1**.

Thanks for your hard work!

**UPD**:  epg_ripper_CA1 doesn't merge too.

**Comment by epgshare01** [comment]
This happens sometimes. Always good to wait another day to see if it happens again.
