### ISSUE TITLE
All Indian Movie Channels Problem

### ISSUE THREAD

**Issue by engrmansoor77** [epgshare01/share01#68]
Dear Developer,
Thanks for the great work.

All Indian Movie Channels shows only"Movie" in current EPG while it shows correct movie names for yesterday and previous days.
It means that the timing for updating its data is not correct. Please check and resolve 
 File name: epg_ripper_IN4.xml 

Channels: 
Zee.Classic.in
Zee.Bollywood.in
Zee.Action.in
Zee.Anmol.Cinema.in
SONY.MAX.2.in
SONY.MAX.HD.in
SONY.MAX.in
SONY.WAH.in
Zee.Cinema.HD.+1.in
Zee.Cinema.HD.in
Zee.Cinema.in
AND.pictures.HD.in
AND.pictures.in
STAR.GOLD.HD.+1.in
Star.GOLD.HD.in
STAR.GOLD.HD.in
STAR.Gold.in
Star.Gold.2.in
Star.Gold.Select.in
Star.Gold.Select.HD.in
STAR.Utsav.Movies.in
UTV.Movies.in
Colors.Cineplex.in
Colors.Cineplex.HD.in
B4U.Kadak.in

**Comment by epgshare01** [comment]
Looks fine.

**Comment by engrmansoor77** [comment]
![Screenshot_20220509-100432_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344265-ea870504-7e78-40e0-842c-9aa5b87c7c1d.jpg)
![Screenshot_20220509-100443_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344270-3848931b-ac33-4601-82ee-bf5da77c5893.jpg)
![Screenshot_20220509-100448_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344273-4854a0e9-382b-4c7c-ac0b-8ae6cb0ded1f.jpg)
![Screenshot_20220509-100427_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344277-b1a6421f-0253-45e5-9e73-3e8263af7650.jpg)


Dear Developer,

Kindly check the attached screenshots taken after update of May 8. There is no movie listing for May 8 onwards, however, it is updated till last day.

Kindly resolve it.

Thanks
