### ISSUE TITLE
A few USA Channels

### ISSUE THREAD

**Issue by agentsix1** [epgshare01/share01#69]
I am refering to all usa channels here

AMC+.us is showing no information

channels missing or not working
Bet jams
bet soul
buzzer
cbn
Missing
Fox Soul
Adult Swim
Hunt Channel
Indieplex
InfoWars
ION Plus
Lifetime Real Women
MTV U
People TV
PIXL
redbull tv
retro plex
Ride TV
RT News
RT DOCUMENTARY 
Showtime Bet
So Yummy!
Tastemade
TV Games Network 2
VSIN
World Fishing Network
Local Now
MARQUEE SPORTS
fubo sports network
fubo sports 1 - 5
WILLOW CRICKET

**Comment by epgshare01** [comment]
Fixed/Added:

AMC+
Bet Jams
Bet Soul
Buzzr TV
Fox Soul
Indieplex
Ion Plus
Lifetime Real Women
MTV U
People TV
PixL
Retroplex
Ride TV
So Yummy
Tastemade
TV Games Network 2
VSIN
World Fishing Network
Marquee Sports Network
Willow Cricket

Showtime Bet = SHOxBET



Can't find:
CBN
Adult Swim in not a US channel. Canada only
Hunt
Infowars
Redbull tv
RT News
RT Documentary
Loacl Now
Fubo Sports Network
Fubo Sports 1 - 5
