### ISSUE TITLE
Korea EPG

### ISSUE THREAD

**Issue by yahn01** [epgshare01/share01#7]
Dear Epgshare 01

First of all, I apologize for replying late as I didn't notice you sent
email until yesterday. Now I noticed that you closed the case. 
Thank you very much doing a great work to share EPG file for everyone to
use.
Incase if you are using webgraber plus to make EPG file then is it possible
to use
http://webgrabplus.com/epg-channels#s146
then to host korean epg.xml file?

If not, https://github.com/wiserain/epg2xml
This is Korean person who developed  this program to create Korean EPG.xml.
it is in Korean but use to create Korean TV xml file.
Incase if you need further information, please let me know,

Thanks

Ahn

**Comment by epgshare01** [comment]
KR1 added. Give it some time to finish.

**Comment by yahn01** [comment]
Thank you very much for your quick response to this.

I will check your page.

Really appreciate it.

Best regards
