### ISSUE TITLE
More Usa Channels

### ISSUE THREAD

**Issue by agentsix1** [epgshare01/share01#70]
Here are a few more I have been unable to find or are broken. Thank you so much for going over the last post I made! Will be looking forward to those updates.

Missing/Broken Channels
ABC News
BNC TV
CBS News
Cheddar Business
LIVENOW FROM FOX
News Nation
SPECTRUM NEWS 1
Fox.Sports.Carolinas.Alternate.HDTV.DirecTV.(FSCRHD).us (Showing no information)
Fox.Sports.Tennessee.Alt..HDTV.DirecTV.(FSTNHD).us (Showing no information)
NBC.Sports.Northwest.(NBCSNW).us (Showing no information)
NBC.Sports.Network.HDTV.(NBCSN).us (Showing no information)
NBC.Sports.Network.Alternate.HDTV.DirecTV.(NBCSAHD).us (Showing no information
NEWSY.us (Showing no information)
News.12.New.Jersey.(NEWS12).us (Showing no information)
Mega.TV.HDTV.Channel.405.(MEGAHD).us (Showing no information)

**Comment by epgshare01** [comment]
Fixed/Added:
ABC News
BNC
CBS News
Cheddar Business
LiveNow
News Nation
Newsy
MEGA TV


Can't find:
Spectrum News 1 = Local Spectrum news channel. No national feed.
Fox Sports is now Bally Sports for all channels I believe.
News 12 NJ
