### ISSUE TITLE
 All Indian Movie Channels Problem

### ISSUE THREAD

**Issue by engrmansoor77** [epgshare01/share01#71]
Dear Developer,

I am reopening this issue. 

Kindly check the attached screenshots taken after update of May 8. There is no movie listing for May 8, however, it is updated till last day. This is happening with almost all channels i mentioned in my earlier issue #68 

Kindly resolve it.

Thanks

![Screenshot_20220509-100427_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344607-f7b22dd1-8038-467e-9b99-9731d1187fa4.jpg)
![Screenshot_20220509-100432_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344615-6dda6f50-fd8a-461a-8d66-ec5901759e1b.jpg)
![Screenshot_20220509-100443_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344618-8ff6257f-3771-430e-be36-0d28e60fe605.jpg)
![Screenshot_20220509-100448_IPTV Pro](https://user-images.githubusercontent.com/67867996/167344621-3f58cf93-c669-449e-a5c5-70bcabec361a.jpg)

**Comment by epgshare01** [comment]
I don't see that issue.
