### ISSUE TITLE
is it possible to add epg for Classic Reruns TV?thx!

### ISSUE THREAD

**Issue by rick999999** [epgshare01/share01#74]
is it possible to add epg for Classic Reruns TV?thx in advance!

https://classicreruns.com/schedule/
or
https://www.ontvtonight.com/guide/listings/channel/3590017754/wkuw-classic-reruns-tv.html

**Comment by epgshare01** [comment]
Added. wait for upload.

**Comment by rick999999** [comment]
thx for your great work! 
but i have checked it yesterday and today.
it still has no body part but just title part.
<channel id="Classic.Reruns.TV.us">
    <icon src="https://cdn.titantv.com/4GLjWWYP_XoOw_3fP7DpaZticyaTDqQQW76cI11r5Sk.png" />
    <url>http://www.classicreruns.com</url>
    <display-name lang="en">Classic Reruns TV</display-name>
  </channel>
