### ISSUE TITLE
Turner Classic Movies HDTV (TCMHD)  no program info

### ISSUE THREAD

**Issue by moonbairn** [epgshare01/share01#76]
Turner Classic Movies HDTV (TCMHD)  no program info

https://github.com/epgshare01/share01/blob/master/epg_ripper_US1.xml.gz

**Comment by epgshare01** [comment]
Turner.Classic.Movies.HDTV.(TCMHD).us

I see data.

**Comment by moonbairn** [comment]
Data finally showed up.  I had to clear cache and restart Shield.  Thanks. Closed.
