### ISSUE TITLE
ability to adding TVG ID's independently

### ISSUE THREAD

**Issue by albilia** [epgshare01/share01#79]
First, Many thanks for the wonderful service.
I would like to know if Is there an option for an end user who works with this repo to be involved in any way in adding TVG IDs independently / locally?
Suppose we work on the same general xml.gz address, with the ability to add only one TVG ID to the file. Too innocent a question? It does not work like that? :)

**Comment by epgshare01** [comment]
Thanks for the offer. But I don't see how it would work. :)
