### ISSUE TITLE
EPG from TVTV.us for IMDBtv and/or Amazon Prime Video?

### ISSUE THREAD

**Issue by geonsey** [epgshare01/share01#83]
Good morning. I am the developer of Free2View TV and I am looking for a good xml source for EPG located at TVTV.us, specifically for the IMDBtv and/or the Amazon Prime Video listings. They all have the most common free TV channels available through many free places and looking for one resource to cover them (since their streams are mainly interchangeable between services/webstreams). Would you consider developing an xml for that allow our Project to use it? Thank you in advance. -Georges B. / The Free2View TV Project.

**Comment by epgshare01** [comment]
Send me a current invite to your discord channel and we can discuss.

**Comment by geonsey** [comment]
Here's an invite for everyone here: https://discord.gg/zV3MwtZ6es
You are all welcome! (Send me a DM if you want to chat privately!)
