### ISSUE TITLE
Request: Only One israeli  channel  : )

### ISSUE THREAD

**Issue by albilia** [epgshare01/share01#84]
Hello, could you please add the channels from this site:

https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/14/%D7%A2%D7%A8%D7%95%D7%A5-14-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99

Live Stream:
https://www.now14.co.il/tochniot_meleot/%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99/

Anyways, thanks for creating this huge repository of program guides 💪 👏 ☺️

**Comment by epgshare01** [comment]
All channel data added from this site. Wait for tomorrow's upload.

**Comment by albilia** [comment]
I apologize in advance for reopening the issue.
After waiting a few days for the file update as you explained, I did not see an EPG added.
Could be because the reason
The channel was formerly called "Channel 20", its tag on share01 is: "Channel.20.il"
In practice, this is not true.
The channel changed its name to "Channel 14".
And this is the relevant EPG regarding the above channel: http://shorturl.at/lJN06

**Comment by albilia** [comment]
> All channel data added from this site. Wait for tomorrow's upload.

I apologize in advance for reopening the issue.
After waiting a few days for the file update as you explained, I did not see an EPG added.
Could be because the reason
The channel was formerly called "Channel 20", its tag on share01 is: "Channel.20.il"
In practice, this is not true.
The channel changed its name to "Channel 14".
And this is the relevant EPG regarding the above channel: http://shorturl.at/lJN06

**Comment by epgshare01** [comment]
I had an error in my script. Wait for tonight's upload.

**Comment by albilia** [comment]
> I had an error in my script. Wait for tonight's upload.

Dear Share01 Dev,
Channel 14 has been added properly and Epg can be seen.
Thank you so much for that. you the best. 
However three channels whose there Epg worked properly stopped pulling Epg.
These are the channels:

1. מכאן.il
2. ערוץ.הקניות.il
3. Hala.TV.il

Again, sorry if I bother. 
btw, I would be happy to receive a guide to learn how to make such a repo :)

**Comment by albilia** [comment]
At 24:00 Israel time, the Epg calibrated by itself without touching anything. Before that ... I deleted Cache in the ISTB app several times and pulled the Epg without success.
As mentioned, at 24:00 the EPG calibrated on its own.
Everything is fine right now, many many thanks for everything :-)
