### ISSUE TITLE
PBS no info or wrong info

### ISSUE THREAD

**Issue by moonbairn** [epgshare01/share01#87]
Thanks for your great EPGs.
Was trying to update all my PBS channels from matthuisman. His epg has been broken 
for about a month now.  So I'm updating those stations with your excellent 
US_LOCALS2 but I've found a few problems.

Twin Cities PBS -  PBS (TPT-DT1) tpt2 St. Paul, MN has no info
WPBT South Florida PBS - PBS (WPBT) West Palm Beach, FL has no info
Ball State PBS - PBS (WIPB) Muncie, IN has no info
PBS Kansas Public Television - PBS (KPTS) Wichita, KS has no info
WXEL South Florida PBS - PBS (WXEL) West Palm Beach, FL has wrong info
WETA - PBS (WETA) HD Washington, DC has wrong info
WEDU PBS - PBS (WEDU) Tampa, FL has wrong info
JAX PBS - PBS (WJCT) Jacksonville, FL has wrong info
WQPT PBS - PBS (WQPT) Quad Cities, IA has wrong info

Tivimate screenshots for each of these can be found on my imgur captured last evening.
https://i.imgur.com/y5DmKpq.jpg
https://i.imgur.com/dkcib47.jpg
https://i.imgur.com/95i8nhj.jpg
https://i.imgur.com/Z94zkQC.jpg
https://i.imgur.com/HYK8uel.jpg
https://i.imgur.com/dYGbNZR.jpg
https://i.imgur.com/YEIajQO.jpg
https://i.imgur.com/7QQbKg7.jpg
https://i.imgur.com/uyLCAWo.jpg

**Comment by epgshare01** [comment]
All fixed. Wait a day before checking.
