### ISSUE TITLE
Few EPG missing -- Indian Channel

### ISSUE THREAD

**Issue by bhanuagarwal73** [epgshare01/share01#92]
B4u Plus
Music India
Bflix Movies
Colors Cineplex Bollywood

![image](https://user-images.githubusercontent.com/38572421/182132359-5711787b-2261-4b51-b8a8-3311f114e9c3.png)
![image](https://user-images.githubusercontent.com/38572421/182132404-1c0d6878-ea8f-4e04-a592-de90d84709aa.png)
![image](https://user-images.githubusercontent.com/38572421/182132447-6900b373-ba75-4fa1-9899-99df4e0e96ef.png)
![image](https://user-images.githubusercontent.com/38572421/182132568-7e1e44a9-a94f-4be6-b507-a6a508971e92.png)

**Comment by epgshare01** [comment]
All channels added. Wait a day for upload.
