### ISSUE TITLE
Missing Channel - Shemaroo Umang -- Indian Channel

### ISSUE THREAD

**Issue by bhanuagarwal73** [epgshare01/share01#95]
#94 not yet resolved. 

I can see the Shemaroo.Umang.in but its showing copied EPG of Shemaroo.TV.in

Please refer the link for guide https://dishnews.in/shemaroo-umang-today-schedule-on-dd-free-dish/

**Comment by epgshare01** [comment]
I have made a change that might fix the issue. Wait for tomorrow night's upload.

**Comment by bhanuagarwal73** [comment]
Working now, thanks buddy. Closing this.

**Comment by bhanuagarwal73** [comment]
@epgshare01  again seeing issue. I am not seeing Shemaroo.Umang.in https://github.com/epgshare01/share01/blob/master/epg_ripper_IN4.txt

**Comment by epgshare01** [comment]
My fault. I have re-added that one. Wait for tonight's upload.
