### ISSUE TITLE
Goldmines Bollywood Missing -- Indian Channel

### ISSUE THREAD

**Issue by bhanuagarwal73** [epgshare01/share01#96]
Please add Goldmines Bollywood formerly known as Dhinchaak 2

https://www.knowledgeskey.com/goldmines-bollywood-today-schedule/
https://logos.fandom.com/wiki/Goldmines_Bollywood?so=search

**Comment by epgshare01** [comment]
Added. Wait for tomorrow night's upload.

**Comment by bhanuagarwal73** [comment]
Working. Closing this.

**Comment by epgshare01** [comment]
Goldmines.in exists.

**Comment by bhanuagarwal73** [comment]
@epgshare01  not goldmines buddy, it should be goldminesbollywood
