### ISSUE TITLE
Wrong Channel Icons - DE1

### ISSUE THREAD

**Issue by Littlericket** [epgshare01/share01#97]
Hi,

the channel icons for DE1 from tvtv.de are wrong. They have to be "https://images.tvtv.de/tvlogo/pro7.svg" (for example) instead of "https://www.tvtv.de/images/senderlogos/pro7.svg".

**Comment by epgshare01** [comment]
Fixed. Wait for tomorrow night's upload.

**Comment by Littlericket** [comment]
Hi @epgshare01, still wrong icon urls.
