### ISSUE TITLE
Colors_Cineplex_Superhits missing -- Indian Channel

### ISSUE THREAD

**Issue by bhanuagarwal73** [epgshare01/share01#99]
Please add the same.

https://en.wikipedia.org/wiki/Colors_Cineplex_Superhits

**Comment by epgshare01** [comment]
Added. Let's see if it works...

**Comment by bhanuagarwal73** [comment]
@epgshare01 not working buddy.

**Comment by epgshare01** [comment]
Unfortunately the one source I have does not seem to work.
